// Дамян Николаев Иванов - ФН: F123976
namespace FitnessTracker.Models;
using LiteDB;

/// <summary>
/// Base class for all database entities, providing common fields like Id and timestamps
/// </summary>
public class BaseEntity
{
    /// <summary>
    /// Primary key for the entity (auto-generated by LiteDB)
    /// </summary>
    [BsonId] public int Id { get; set; }
    
    /// <summary>
    /// Timestamp when the entity was created
    /// </summary>
    public DateTime DateCreated { get; set; } = DateTime.UtcNow;
    
    /// <summary>
    /// Timestamp when the entity was last modified
    /// </summary>
    public DateTime DateModified { get; set; } = DateTime.UtcNow;
    
    /// <summary>
    /// Updates the DateModified timestamp to current UTC time
    /// </summary>
    public void MarkUpdated() => DateModified = DateTime.UtcNow;
}